import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <nav className="border-b-2 border-black">
          <div className="bg-cyan-500 flex justify-between p-4 items-center relative text-capuchino overflow-hidden">
            <div className="bg-zinc-800 w-40 h-40 absolute rotate-45 left-0"></div>
            <h1 className="text-lg z-1 text-crema">
              <span className="text-2xl text-red-600 font-bold">N</span>ext.js
              Cepeda
            </h1>

            {/* links */}

            <div className="flex gap-5 text-lg text-white font-sans relative">
              {/*link Inicio */}
              <div className="flex group">
                <Link
                  href="."
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Inicio
                  </span>
                  <div className="bg-green-700 w-35 h-35 -mt-35 -right-8.5 absolute rotate-45 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*link about */}
              <div className="flex group">
                <Link
                  href="/about"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    About
                  </span>
                  <div className="bg-green-600 w-35 h-35 absolute rotate-45 -mt-8 -right-8 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*link Blog */}
              <div className="flex group">
                <Link
                  href="/blog"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Blogs
                  </span>
                  <div className="bg-green-500 w-35 h-35 -mt-35 -right-8 absolute rotate-45 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*este notas */}
              <div className="flex group">
                <Link
                  href="/notes"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Notas
                  </span>
                  <div className="bg-green-400 w-35 h-35 absolute rotate-45 -mt-8 -right-8 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {children}

        <footer className="border-t-2 border-black mt-auto">
          <div className="bg-cielo flex mx-auto justify-center p-4 items-center relative overflow-hidden ">
            <div className="bg-carbon w-40 h-70 absolute rotate-45"></div>
            <h1 className="text-zinc-500 z-1">
              <span className="text-2xl text-red-900 font-bold">N</span>ext.js
              Cepeda
            </h1>
          </div>
        </footer>
      </body>
    </html>
  );
}
