import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <nav className="border-b-2 border-black">
          <div className="bg-cielo flex justify-between p-4 items-center relative overflow-hidden text-capuchino">
            <div className="bg-fondo w-40 h-70 absolute rotate-45 left-0"></div>
            <h1 className="text-lg z-1 text-crema">
              <span className="text-2xl text-red-600 font-bold">N</span>ext.js
              Cepeda
            </h1>

            {/* links */}
            <div className="flex gap-5 text-lg text-white font-sans relative">
              {/*link Inicio */}
              <div className="flex group">
                <Link
                  href="."
                  className="text-center px-3.5 transition-all duration-300 group-hover:text-capuchino rounded-full z-10"
                >
                  Inicio
                </Link>
                <div className="bg-green-900 w-35 h-60 absolute -rotate-45 -my-3.5 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer"></div>
              </div>
              {/*link Blog */}
              <div className="flex group">
                <Link
                  href="/blog"
                  className=" text-center px-4  transition-all duration-300 group-hover:text-capuchino rounded-full z-10"
                >
                  Blog
                </Link>
                <div className="bg-green-800 w-35 h-60 absolute rotate-45 bottom-0 -my-2.5 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer"></div>
              </div>
              {/*link About */}
              <div className="flex group">
                <Link
                  href="/about"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10"
                >
                  About
                </Link>
                <div className="bg-green-700 w-35 h-60 absolute -rotate-45 -my-3 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer"></div>
              </div>
              {/*link Notas */}
              <div className="flex group">
                <Link
                  href="/notas"
                  className=" text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10"
                >
                  Notas
                </Link>
                <div className="bg-green-600 w-35 h-60 absolute rotate-45 bottom-0 -my-3 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer"></div>
              </div>
              <div className="bg-green-500 w-35 h-60 absolute -rotate-45 -right-40 -my-3 transition-all duration-300 hover:bg-white hover:text-capuchino cursor-pointer"></div>
            </div>
          </div>
        </nav>

        {children}

        <footer className="border-t-2 border-black mt-auto">
          <div className="bg-cielo flex mx-auto justify-center p-4 items-center relative overflow-hidden ">
            <div className="bg-carbon w-40 h-70 absolute rotate-45"></div>
            <h1 className="text-zinc-500 z-1">
              <span className="text-2xl text-red-900 font-bold">N</span>ext.js
              Cepeda
            </h1>
          </div>
        </footer>
      </body>
    </html>
  );
}
