import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen">
        <nav className="border-b-2 border-black bg-[url(/nitro.jpg)]">
          <div className="bg-black/25 flex justify-between p-4 items-center relative text-capuchino overflow-hidden">
            <div className="bg-zinc-800 w-40 h-40 absolute rotate-45 left-0"></div>
            <h1 className="text-lg z-1 text-crema">
              <span className="text-2xl text-red-600 font-bold">N</span>ext.js
              Cepeda
            </h1>

            {/* links */}

            <div className="flex gap-5 text-lg text-white font-sans relative">
              {/*link Inicio */}
              <div className="flex group">
                <Link
                  href="."
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Inicio
                  </span>
                  <div className="bg-green-700/70 w-35 h-35 -mt-35 -right-8.5 absolute rotate-45 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*link about */}
              <div className="flex group">
                <Link
                  href="/about"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    About
                  </span>
                  <div className="bg-green-600/70 w-35 h-35 absolute rotate-45 -mt-8 -right-8 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*link Blog */}
              <div className="flex group">
                <Link
                  href="/blog"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Blogs
                  </span>
                  <div className="bg-green-500/70 w-35 h-35 -mt-35 -right-8 absolute rotate-45 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
              {/*este notas */}
              <div className="flex group">
                <Link
                  href="/notes"
                  className="text-center px-3 transition-all duration-300 group-hover:text-capuchino rounded-full z-10 relative"
                >
                  <span className="text-white relative z-10 transition-all duration-300 group-hover:text-capuchino font-medium ml-2">
                    Notas
                  </span>
                  <div className="bg-green-400/70 w-35 h-35 absolute rotate-45 -mt-8 -right-8 transition-all duration-300 group-hover:bg-white group-hover:text-capuchino cursor-pointer z-0"></div>
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {children}

        <footer className="mt-auto min-h-30 bg-zinc-800 flex justify-between items-center">
          <div className="min-w-30 h30 p-5 text-2xl font-bold">
            <h1 className="bg-clip-text text-transparent bg-linear-45 from-lime-300 to-green-900">
              NATURALEZA
            </h1>
            <p className="text-sm font-light">
              la mejor manera de conectarte con el mundo <br />
              es visitando nuestros productos.
            </p>
          </div>
          <div className="min-w-30 h30 p-5 border-x-2 px-30 text-zinc-900">
            <h3 className="text-zinc-500 mt-auto ">
              ©️2026 - Derechos reservados Cepeda Caceres Emanuel
            </h3>
          </div>
          <div className="min-w-30 h30 p-5">
            <Image
              src="redondo.svg"
              width={70}
              height={70}
              alt="Picture of the author"
              className="drop-shadow-[0_1.2px_3px_rgba(255,255,255,1)]"
            />
          </div>
          {/* 
          
          <div className="bg-cielo/15 flex mx-auto justify-center p-4 items-center relative overflow-hidden ">
            <div className="bg-carbon w-40 h-70 absolute rotate-45"></div>
            <h1 className="text-zinc-500 z-1">
              <span className="text-2xl text-red-900 font-bold">N</span>ext.js
              Cepeda
            </h1>
          </div>
              */}
        </footer>
      </body>
    </html>
  );
}
